apiVersion: v1
kind: Secret
metadata:
  name: dispatch-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  REDIS_ADDR: {{ .Values.secrets.REDIS_ADDR | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.KAFKA_BROKERS | quote }}
