{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.api.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
{{- if .Values.consumer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.consumer.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.consumer.serviceAccount.annotations | nindent 4 }}
{{- end }}
